import { ColumnMetadata } from '../types/table-metadata';
import { DEAL_STAGES } from './deals';

export const COMPANY_TABLE_METADATA: ColumnMetadata[] = [
  {
    id: 'companyName',
    header: 'Company',
    fieldType: 'entity',
    dataType: 'text',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      entityType: 'company',
      hrefTemplate: '/companies/{id}',
    },
  },
  {
    id: 'website',
    header: 'Website',
    fieldType: 'text',
    dataType: 'text',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      render: 'link',
      hrefTemplate: '{value}',
    },
  },
  {
    id: 'linkedinUrl',
    header: 'LinkedIn',
    fieldType: 'text',
    dataType: 'text',
    sortable: false,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      render: 'link',
      hrefTemplate: '{value}',
    },
  },
  {
    id: 'owners',
    header: 'Owner',
    fieldType: 'relation',
    dataType: 'json',
    sortable: false,
    filterable: true,
    searchable: true,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      format: 'owner',
    },
  },
  {
    id: 'createdAt',
    header: 'Created',
    fieldType: 'date',
    dataType: 'date',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      format: 'date',
    },
  },
];

export const CONTACT_TABLE_METADATA: ColumnMetadata[] = [
  {
    id: 'name',
    header: 'Name',
    fieldType: 'entity',
    dataType: 'text',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      entityType: 'contact',
      hrefTemplate: '/contacts/{id}',
    },
  },
  {
    id: 'email',
    header: 'Email',
    fieldType: 'text',
    dataType: 'text',
    sortable: false,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      render: 'email',
      accessorKey: 'email',
    },
  },
  {
    id: 'phone',
    header: 'Phone',
    fieldType: 'text',
    dataType: 'text',
    sortable: false,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      render: 'phone',
      accessorKey: 'phone',
    },
  },
  {
    id: 'owners',
    header: 'Owner',
    fieldType: 'relation',
    dataType: 'json',
    sortable: false,
    filterable: true,
    searchable: true,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      format: 'owner',
    },
  },
  {
    id: 'createdAt',
    header: 'Created',
    fieldType: 'date',
    dataType: 'date',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      format: 'date',
    },
  },
];

export const MEETING_TABLE_METADATA: ColumnMetadata[] = [
  {
    id: 'name',
    header: 'Title',
    fieldType: 'entity',
    dataType: 'text',
    sortable: true,
    filterable: false,
    searchable: true,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      hrefTemplate: '/meeting/{id}',
    },
  },
  {
    id: 'platform',
    header: 'Platform',
    fieldType: 'select',
    dataType: 'text',
    sortable: false,
    filterable: false,
    searchable: false,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      format: 'stage',
      render: 'platform-icon',
      options: [
        { label: 'Google Meet', value: 'GOOGLE_MEET' },
        { label: 'Zoom', value: 'ZOOM' },
        { label: 'MS Teams', value: 'MS_TEAMS' },
      ],
      iconMap: {
        GOOGLE_MEET: '/icons/google-meet.svg',
        ZOOM: '/icons/zoom.svg',
        MS_TEAMS: '/icons/ms-teams.svg',
      },
    },
  },
  {
    id: 'url',
    header: 'Join',
    fieldType: 'text',
    dataType: 'text',
    sortable: false,
    filterable: false,
    searchable: false,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      render: 'join-button',
    },
  },
  {
    id: 'scheduledAt',
    header: 'Date',
    fieldType: 'date',
    dataType: 'date',
    sortable: true,
    filterable: false,
    searchable: false,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      format: 'date',
    },
  },
  {
    id: 'status',
    header: 'Status',
    fieldType: 'select',
    dataType: 'text',
    sortable: false,
    filterable: false,
    searchable: false,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      render: 'badge',
      format: 'stage',
      options: [
        { label: 'Pending', value: 'PENDING' },
        { label: 'In Progress', value: 'IN_PROGRESS' },
        { label: 'Processing', value: 'PROCESSING' },
        { label: 'Completed', value: 'COMPLETED' },
        { label: 'Failed', value: 'FAILED' },
        { label: 'Rejected', value: 'REJECTED' },
      ],
      colorMap: {
        pending: 'zinc',
        in_progress: 'blue',
        processing: 'blue',
        completed: 'green',
        failed: 'red',
        rejected: 'red',
      },
    },
  },
];

export const DEAL_TABLE_METADATA: ColumnMetadata[] = [
  {
    id: 'title',
    header: 'Title',
    fieldType: 'entity',
    dataType: 'text',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      entityType: 'deal',
      hrefTemplate: '/deals/{id}',
    },
  },
  {
    id: 'value',
    header: 'Value',
    fieldType: 'currency',
    dataType: 'number',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      currency: 'USD',
      format: 'currency',
    },
  },
  {
    id: 'stage',
    header: 'Stage',
    fieldType: 'select',
    dataType: 'text',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      render: 'badge',
      format: 'stage',
      options: [...DEAL_STAGES],
      colorMap: {
        prospecting: 'zinc',
        qualification: 'blue',
        proposal: 'yellow',
        negotiation: 'yellow',
        closed_won: 'green',
        closed_lost: 'red',
      },
    },
  },
  {
    id: 'probability',
    header: 'Probability',
    fieldType: 'number',
    dataType: 'number',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      accessorKey: 'probability',
    },
  },
  {
    id: 'owners',
    header: 'Owner',
    fieldType: 'relation',
    dataType: 'json',
    sortable: false,
    filterable: true,
    searchable: true,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      format: 'owner',
    },
  },
  {
    id: 'expectedCloseDate',
    header: 'Expected Close',
    fieldType: 'date',
    dataType: 'date',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      format: 'date',
    },
  },
];
