import { ColumnMetadata } from '../types/table-metadata';

export const COMPANY_TABLE_METADATA: ColumnMetadata[] = [
  {
    id: 'companyName',
    header: 'Company',
    fieldType: 'entity',
    dataType: 'text',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      entityType: 'company',
      hrefTemplate: '/companies/{id}',
    },
  },
  {
    id: 'website',
    header: 'Website',
    fieldType: 'text',
    dataType: 'text',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      render: 'link',
      hrefTemplate: '{value}',
    },
  },
  {
    id: 'linkedinUrl',
    header: 'LinkedIn',
    fieldType: 'text',
    dataType: 'text',
    sortable: false,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      render: 'link',
      hrefTemplate: '{value}',
    },
  },
  {
    id: 'owners',
    header: 'Owner',
    fieldType: 'text',
    dataType: 'json',
    sortable: false,
    filterable: true,
    searchable: true,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      format: 'owner',
    },
  },
  {
    id: 'createdAt',
    header: 'Created',
    fieldType: 'date',
    dataType: 'date',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      format: 'date',
    },
  },
];

export const CONTACT_TABLE_METADATA: ColumnMetadata[] = [
  {
    id: 'name',
    header: 'Name',
    fieldType: 'entity',
    dataType: 'text',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      entityType: 'contact',
      hrefTemplate: '/contacts/{id}',
    },
  },
  {
    id: 'email',
    header: 'Email',
    fieldType: 'text',
    dataType: 'text',
    sortable: false,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      render: 'email',
      accessorKey: 'email',
    },
  },
  {
    id: 'phone',
    header: 'Phone',
    fieldType: 'text',
    dataType: 'text',
    sortable: false,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      render: 'phone',
      accessorKey: 'phone',
    },
  },
  {
    id: 'owners',
    header: 'Owner',
    fieldType: 'text',
    dataType: 'json',
    sortable: false,
    filterable: true,
    searchable: true,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      format: 'owner',
    },
  },
  {
    id: 'createdAt',
    header: 'Created',
    fieldType: 'date',
    dataType: 'date',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      format: 'date',
    },
  },
];

export const DEAL_TABLE_METADATA: ColumnMetadata[] = [
  {
    id: 'title',
    header: 'Title',
    fieldType: 'entity',
    dataType: 'text',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      entityType: 'deal',
      hrefTemplate: '/deals/{id}',
    },
  },
  {
    id: 'value',
    header: 'Value',
    fieldType: 'currency',
    dataType: 'number',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      currency: 'USD',
      format: 'currency',
    },
  },
  {
    id: 'stage',
    header: 'Stage',
    fieldType: 'select',
    dataType: 'text',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      render: 'badge',
      format: 'stage',
      options: [
        { label: 'Negotiation', value: 'negotiation' },
        { label: 'Proposal', value: 'proposal' },
        { label: 'Qualification', value: 'qualification' },
        { label: 'Prospecting', value: 'prospecting' },
        { label: 'Closed Won', value: 'closed_won' },
        { label: 'Closed Lost', value: 'closed_lost' },
      ],
      colorMap: {
        prospecting: 'zinc',
        qualification: 'blue',
        proposal: 'yellow',
        negotiation: 'yellow',
        closed_won: 'green',
        closed_lost: 'red',
      },
    },
  },
  {
    id: 'probability',
    header: 'Probability',
    fieldType: 'number',
    dataType: 'number',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: true,
    isVisible: true,
    default: true,
    config: {
      accessorKey: 'probability',
    },
  },
  {
    id: 'owners',
    header: 'Owner',
    fieldType: 'text',
    dataType: 'json',
    sortable: false,
    filterable: true,
    searchable: true,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      format: 'owner',
    },
  },
  {
    id: 'expectedCloseDate',
    header: 'Expected Close',
    fieldType: 'date',
    dataType: 'date',
    sortable: true,
    filterable: true,
    searchable: true,
    editable: false,
    isVisible: true,
    default: true,
    config: {
      format: 'date',
    },
  },
];
